# This is a TOML document. Boom
pub = "natsst"

[discovery]
    nodes = ["127.0.0.1:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["10.211.55.5:9092"]
[nats]
    cluster = "test-cluster"
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    durable = "history"
    brokers = "nats://localhost:4222"
    ackinbox = "ack"
[room]
    signal = "100ms"
    batch = 50
    #idle = "1000s"
[comet]
    routineChan=32
    routineSize=1024
